FROM mcr.microsoft.com/dotnet/sdk:7.0
EXPOSE 5000
#COPY ./nop/ /nop
#WORKDIR /nop
#CMD ["dotnet", "Nop.Web.dll", "--urls", "http://0.0.0.0:5000"]

#docker container run -d --name nopdb -v nopdb:/var/lib/mysql -e "MYSQL_ROOT_PASSWORD=nop12345" -e "MYSQL_USER=nop" -e "MYSQL_PASSWORD=nop12345" -e "MYSQL_DATABASE=nop" mysql:8.0-debian

#inspect the nop db and find the IP address